# http://fishi.devtail.io/weblog/2016/04/02/testing-ansible-ansible-vault-travis-ci/

language: python
python: '2.7'
sudo: true
addons:
  apt:
    packages:
    - python-pip
before_install:
- openssl aes-256-cbc -K $encrypted_3723425d7017_key -iv $encrypted_3723425d7017_iv
  -in secrets.yml.enc -out group_vars/secrets.yml -d
- openssl aes-256-cbc -K $encrypted_3723425d7017_key -iv $encrypted_3723425d7017_iv
  -in clients.yml.enc -out group_vars/clients.yml -d
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook eduroam_idp.yml -i inventories/development --syntax-check
- ansible-playbook eduroam_idp.yml -i inventories/development
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
