---
- name: Gather OS specific variables
  hosts: idp
  become: True
  gather_facts: True
  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "group_vars/distributions/{{ ansible_distribution }}-{{ ansible_distribution_release}}.yml"
        - "group_vars/distributions/{{ ansible_distribution }}.yml"
      tags: clients


- name: Install eduroam Identity Provider
  hosts: idp
  become: True
  gather_facts: True
  vars_files:
    - group_vars/secrets.yml
    - group_vars/clients.yml
    - group_vars/radius_flr.yml
    - group_vars/template
  roles:
    - freeradius
    - { role: eapol_test, when: play_eapol == True }
    - { role: winauth, when: win_auth.enabled == True }

  handlers:
    - name: restart freeradius
      service: name={{ radius.name }} state=restarted
