- name: Reduce Reject Delay
  replace:
    dest: "{{radius.config_path}}/radiusd.conf"
    regexp: 'reject_delay = 1'
    replace: 'reject_delay = 0'
  notify: restart freeradius

# This was no longer needed as dictionary( for freeradius 3.0.16)
# already had all elements to be added
# - name: Copy dictionary with Operator-Name
#   copy:
#     src: files/dictionary
#     dest: "{{ radius.config_path }}/dictionary"
#     backup: yes
#   notify: restart freeradius

# - name: Edit dictionary to add Operator Name
#   lineinfile: dest=""{{ radius.config_path }}/dictionary" regexp="^Operator-Name"  line="ATTRIBUTE  Operator-Name     126  string"

- name: checking for Operator Name in dictionary
  shell: cat {{ radius.config_path }}/dictionary | grep Operator-Name | wc -l
  register: test_grep

- debug: msg="{{test_grep.stdout}}"

- name: adding Operator Name in dictionary
  lineinfile: dest="{{ radius.config_path }}/dictionary" line="ATTRIBUTE  Operator-Name     126  string"
  when: test_grep.stdout == "0"

# Fitted it for Ugandan radius proxies for both client and proxy.conf
- name: Copy clients configuration
  template:
    src: clients.conf.j2
    dest: "{{ radius.config_path }}/clients.conf"
    backup: yes
  tags: clients
  notify: restart freeradius

- name: Copy proxy configuration
  template:
    src: proxy.conf.j2
    dest: "{{radius.config_path}}/proxy.conf"
    backup: yes
  notify: restart freeradius

- name: Copy eap configuration
  template:
    src: eap.conf.j2
    dest: "{{radius.config_path}}/eap.conf"
    backup: yes
  notify: restart freeradius

#For AD, another role is to be set up in later updates
- name: Copy LDAP module if enabled
  template:
    src: ldap-modules.j2
    dest: "{{radius.config_path}}/mods-available/ldap"
    backup: yes
  notify: restart freeradius
  when: ldap.enabled == True

- name: Enable LDAP module if enabled
  file:
    src: "{{radius.config_path}}/mods-available/ldap"
    dest: "{{radius.config_path}}/mods-enabled/ldap"
    state: link
  notify: restart freeradius
  when: ldap.enabled == True

- name: Add test user if enabled
  template:
    src: users.j2
    dest: "{{radius.config_path}}/users"
    backup: yes
  notify: restart freeradius
  when: file.enabled == True

- name: Copy sites/eduroam
  template:
    src: sites_default-eduroam.j2
    dest: "{{radius.config_path}}/sites-available/eduroam"
  notify: restart freeradius

- name: Enable sites/eduroam
  file:
    src: "{{radius.config_path}}/sites-available/eduroam"
    dest: "{{radius.config_path}}/sites-enabled/eduroam"
    state: link
  notify: restart freeradius

- name: Copy sites/eduroam-inner-tunnel
  template:
    src: sites_eduroam-inner-tunnel.j2
    dest: "{{radius.config_path}}/sites-available/eduroam-inner-tunnel"
  notify: restart freeradius

- name: Enable sites/eduroam-inner-tunnel
  file:
    src: "{{radius.config_path}}/sites-available/eduroam-inner-tunnel"
    dest: "{{radius.config_path}}/sites-enabled/eduroam-inner-tunnel"
    state: link
  notify: restart freeradius
