- name: Install Freeradius
  package: 
    name: freeradius
    state: latest

- name: Install LDAP module if enabled
  package: 
    name: freeradius-ldap
    state: latest
  when: ldap.enabled == True

- name: Install libselinux-python and freeradius-utils on RedHat
  package: 
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - freeradius-utils
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'